name: Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4

    - name: Extract version
      id: get_version
      run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push frontend
      id: build-frontend
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Containerfile.frontend
        push: ${{ github.event_name != 'pull_request' }}
        tags: ghcr.io/${{ github.repository_owner }}/chex-mix-timer-frontend:latest,
              ghcr.io/${{ github.repository_owner }}/chex-mix-timer-frontend:${{ github.sha }},
              ghcr.io/${{ github.repository_owner }}/chex-mix-timer-frontend:v${{ steps.get_version.outputs.VERSION }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4

    - name: Extract version
      id: get_version
      run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push backend
      id: build-backend
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Containerfile.backend
        push: ${{ github.event_name != 'pull_request' }}
        tags: ghcr.io/${{ github.repository_owner }}/chex-mix-timer-backend:latest,
              ghcr.io/${{ github.repository_owner }}/chex-mix-timer-backend:${{ github.sha }},
              ghcr.io/${{ github.repository_owner }}/chex-mix-timer-backend:v${{ steps.get_version.outputs.VERSION }}
        cache-from: type=gha
        cache-to: type=gha,mode=max